[package]
name = "advent_of_code_2021"
version = "0.1.0"
authors = ["raymondk <raymond.kalander@gmail.se>"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
permute = "0.1.0"
priority-queue = "1.2.1"
regex = "1.5.4"
